/* Type for objects containing strings representing the lines of the I Ching hexagram.
 * Set index signature to `number` so we can look up the line type using
 * the integer values from the hexagram generated by the CastHexagram class */

export type HexagramLines = {
  [index: number]: string;
};
